name: Java CI with Maven

on:
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn test
      - name: Build Docker image
        run: |
          docker build -t tests-cicd .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name my-tests-cicd-container tests-cicd

      - name: Wait for the application to start
        run: |
          sleep 10

      - name: Send a request to the application
        run: |
          curl -f http://localhost:8080/api/hello

      - name: Stop and remove Docker container
        run: |
          docker stop your_container_name
          docker rm your_container_name